---
- name: Deploy Secure SSH Configuration (Template)
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    # SECURITÃ‰ CRITIQUE : Validation avant application
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart SSH